In [1]:
import numpy as np

In [11]:
## Exploring different ways of copying /referencing arrays
arr_original = np.arange(0,9,1)
print(f"Original Array {arr_original}")

## Explore Memory Reference
arr_by_ref = arr_original
print(f"Array by reference {arr_by_ref}")

arr_by_ref[0] = 100
print(f"Original Array: {arr_original} \n Reference Array: {arr_by_ref}")

## Copying Array
arr_copy = arr_original.copy()
arr_copy[0] = 20
print(f"Original Array: {arr_original} \n Copy Array: {arr_copy}")

## Array View
arr_view = arr_original.view()
print(f"Array View: {arr_view}")

arr_view[0] = 300
print(f"Original Array: {arr_original} \n View Array: {arr_view}")

arr_view2 = arr_original.view(np.int16)
arr_original[0] = 66000
print(f"Original Array: {arr_original} \n View Array: {arr_view2}")



Original Array [0 1 2 3 4 5 6 7 8]
Array by reference [0 1 2 3 4 5 6 7 8]
Original Array: [100   1   2   3   4   5   6   7   8] 
 Reference Array: [100   1   2   3   4   5   6   7   8]
Original Array: [100   1   2   3   4   5   6   7   8] 
 Copy Array: [20  1  2  3  4  5  6  7  8]
Array View: [100   1   2   3   4   5   6   7   8]
Original Array: [300   1   2   3   4   5   6   7   8] 
 View Array: [300   1   2   3   4   5   6   7   8]
Original Array: [66000     1     2     3     4     5     6     7     8] 
 View Array: [464   1   0   0   1   0   0   0   2   0   0   0   3   0   0   0   4   0
   0   0   5   0   0   0   6   0   0   0   7   0   0   0   8   0   0   0]


In [15]:
## TODO: Iterate over all elements in the array and print the sum using 1 loop

numpy_array = np.array([[1,2,3],
                        [4,5,6],
                        [7,8,9]])

# Creates a copy
sum_ft = 0
print(numpy_array.flatten())
for elem in numpy_array.flatten():
    sum_ft+=elem

print(f"Sum flatten: {sum_ft}")

sum = 0

for elem in np.nditer(numpy_array):
    sum += elem
    print(f"Elem: {elem}")
print(sum)


[1 2 3 4 5 6 7 8 9]
Sum flatten: 45
Elem: 1
Elem: 2
Elem: 3
Elem: 4
Elem: 5
Elem: 6
Elem: 7
Elem: 8
Elem: 9
45


In [17]:
## Concatenation of np arrays

first_array = np.arange(0,3)
second_array = np.arange(9,12)

new_array = first_array + second_array

print(f"New Array: {new_array} \n is base {new_array.base==None}")

con_array = np.concatenate((first_array, second_array))

print(f"Con Array: {con_array} \n is base {con_array.base==None}")

New Array: [ 9 11 13] 
 is base True
Con Array: [ 0  1  2  9 10 11] 
 is base True


In [29]:
array_2d_org = np.arange(0,9).reshape(3,3)
print(f"Array 2d Original: \n {array_2d_org}")

### Approach 1
np.concatenate((array_2d_org,second_array.reshape(1,3)))

### Approach 2
adding_1_row = np.vstack((array_2d_org, second_array))

print(f"\n Adding 1 row: \n {adding_1_row}")

print(np.concatenate((array_2d_org, second_array.reshape(3,1)), axis=1))

print(np.hstack((array_2d_org, second_array.reshape(3,1))))


Array 2d Original: 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

 Adding 1 row: 
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2  9]
 [ 3  4  5 10]
 [ 6  7  8 11]]
[[ 0  1  2  9]
 [ 3  4  5 10]
 [ 6  7  8 11]]
